sudo: required
dist: trusty
language: objective-c
osx_image: xcode10.1

cache:
  - npm
  - bundler

addons:
  chrome: beta

before_install:
  - nvm install --lts
  - nvm use --lts
  - npm install -g cordova ionic @angular/cli
  - npm install
  # fastlane
  # check if LANG US is really correct
  - if [ "$TRAVIS_BRANCH" = "master" ]; then export LC_ALL=en_US.UTF-8; fi
  - if [ "$TRAVIS_BRANCH" = "master" ]; then export LANG=en_US.UTF-8; fi
  - if [ "$TRAVIS_BRANCH" = "master" ]; then bundle install; fi
  - if [ "$TRAVIS_BRANCH" = "master" ]; then bundle update; fi
  - if [ "$TRAVIS_BRANCH" = "master" ]; then sudo gem install fastlane -NV; fi

script:
  - npm run lint
  - npm run test-ci
  - ionic build --prod -- --base-href "/friendlib-app/"
  - if [ "$TRAVIS_BRANCH" = "master" ]; then bundle exec fastlane beta; fi

after_success:
  - if [ "$TRAVIS_BRANCH" = "master" ]; then chmod +x .travis/commit_push.bash; fi
  - if [ "$TRAVIS_BRANCH" = "master" ]; then .travis/commit_push.bash; fi

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local_dir: www
