sudo: required
dist: trusty
language: node_js
node_js:
  - "8"

apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - npm install -g cordova ionic
  - npm install -g

script:
  - npm run lint
  - npm run test-ci
