sudo: required
dist: trusty
language: node_js
node_js:
  - "8"

apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - npm install -g cordova ionic

script:
  - npm run lint
  - npm run test-ci
  - ionic build --prod -- --base-href "/friendlib-app/"

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local_dir: www
