# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    setup_ci(provider: 'travis')

    match(readonly: true, git_url: ENV['CERTIFICATES_REPO'])

    cordova(platform: 'ios', release: true, build_flag: ['-UseModernBuildSystem=0'])

    upload_to_testflight(ipa: ENV['CORDOVA_IOS_RELEASE_BUILD_PATH'], skip_waiting_for_build_processing: true)
  end


  lane :dev do

    match(type: 'development', readonly: false, git_url: ENV['CERTIFICATES_REPO'])

    cordova(platform: 'ios', release: true, build_flag: ['-UseModernBuildSystem=0'])
  end
end
